Controllers/VistaPerfilSupervisorController.cs
using Proyecto_Cartilla_Autocontrol.Models;
using Proyecto_Cartilla_Autocontrol.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;
using System.Web.Configuration;
using System.Threading.Tasks;
using System.Runtime.Caching;


namespace Proyecto_Cartilla_Autocontrol.Controllers
{
    public class VistaPerfilSupervisorController : Controller
    {
        public ObraManzanoFinal db { get; set; }

        public VistaPerfilSupervisorController()
        {
            db = new ObraManzanoFinal();
        }

        // GET: VistaPerfilITO
        public static bool actualizacionEditCartilla = false;

        public ActionResult Index()
        {
            var usuarioAutenticado = (USUARIO)Session["UsuarioAutenticado"];
            ViewBag.UsuarioAutenticado = usuarioAutenticado;

            if (usuarioAutenticado != null)
            {
                // Obtiene la lista de IDs de obras a las que el usuario tiene acceso
                var obrasIds = db.ACCESO_OBRAS
                                 .Where(a => a.usuario_id == usuarioAutenticado.usuario_id)
                                 .Select(a => a.obra_id)
                                 .ToList();

                // Obtiene la lista de IDs de cartillas a las que el usuario tiene acceso
                var cartillasIds = db.ACCESO_CARTILLA
                                     .Where(ac => ac.USUARIO_usuario_id == usuarioAutenticado.usuario_id)
                                     .Select(ac => ac.CARTILLA_cartilla_id)
                                     .ToList();

                // Filtra las cartillas basándose en las obras a las que el usuario tiene acceso
                var cartillas = db.CARTILLA
                    .Include(c => c.ACTIVIDAD)
                    .Include(c => c.ESTADO_FINAL)
                    .Include(c => c.OBRA)
                    .Where(c => obrasIds.Contains(c.OBRA_obra_id) && cartillasIds.Contains(c.cartilla_id));

                return View(cartillas.ToList());
            }
            else
            {
                // Maneja el caso en el que el usuario no esté autenticado correctamente
                return RedirectToAction("Login", "Account"); // Redirige a la página de inicio de sesión u otra página adecuada
            }
        }


        public ActionResult ConsultaRevision(int id)
        {
            var cartilla = db.CARTILLA.FirstOrDefault(c => c.cartilla_id == id);
            if (cartilla != null)
            {
                var viewModel = new CartillasViewModel
                {
                    Cartilla = cartilla,
                    DetalleCartillas = db.DETALLE_CARTILLA.Where(d => d.CARTILLA_cartilla_id == id).ToList(),
                    ActividadesList = db.ACTIVIDAD.ToList(),
                    ElementosVerificacion = db.ITEM_VERIF.ToList(),
                    InmuebleList = db.INMUEBLE.ToList(),
                    EstadoFinalList = db.ESTADO_FINAL.ToList()
                };
                int obraId = cartilla.OBRA_obra_id;
                ViewBag.LoteList = new SelectList(
                    db.LOTE_INMUEBLE.Where(l => l.OBRA_obra_id == obraId && l.INMUEBLE.Any(i => i.DETALLE_CARTILLA.Any(dc => dc.CARTILLA_cartilla_id == id)))
                                    .Select(l => new { l.lote_id, l.abreviatura }).ToList(),
                    "lote_id", "abreviatura"
                );

                ViewBag.InmueblePorLote = new SelectList(
                    db.INMUEBLE.Where(i => i.LOTE_INMUEBLE.OBRA_obra_id == obraId && i.DETALLE_CARTILLA.Any(dc => dc.CARTILLA_cartilla_id == id))
                               .Select(i => new { i.inmueble_id, i.codigo_inmueble }).ToList(),
                    "inmueble_id", "codigo_inmueble"
                );
                return View(viewModel);
            }
            return RedirectToAction("Index", "Cartilla");
        }


        [HttpPost]
        public ActionResult ConsultaRevision(CartillasViewModel viewModel, List<DETALLE_CARTILLA> DetalleCartillas)
        {

            // Si llegamos aquí, hay un error, retornamos a la vista con el ViewModel
            ViewBag.LoteList = new SelectList(db.LOTE_INMUEBLE.ToList(), "lote_id", "abreviatura");
            ViewBag.InmueblePorLote = new SelectList(db.INMUEBLE.ToList(), "inmueble_id", "codigo_inmueble");
            viewModel.ActividadesList = db.ACTIVIDAD.ToList();
            viewModel.ElementosVerificacion = db.ITEM_VERIF.ToList();
            viewModel.InmuebleList = db.INMUEBLE.ToList();
            viewModel.EstadoFinalList = db.ESTADO_FINAL.ToList();
            return View(viewModel);
        }

       
        public ActionResult EditarCartilla(int id)
        {
            var cartilla = db.CARTILLA.FirstOrDefault(c => c.cartilla_id == id);

            if (cartilla != null)
            {
                var viewModel = new CartillasViewModel
                {
                    Cartilla = cartilla,
                    DetalleCartillas = db.DETALLE_CARTILLA.Where(d => d.CARTILLA_cartilla_id == id).ToList(),
                    ActividadesList = db.ACTIVIDAD.ToList(),
                    ElementosVerificacion = db.ITEM_VERIF.ToList(),
                    InmuebleList = db.INMUEBLE.ToList(),
                    EstadoFinalList = db.ESTADO_FINAL.ToList()
                };

                int obraId = cartilla.OBRA_obra_id;
                ViewBag.LoteList = new SelectList(
                    db.LOTE_INMUEBLE.Where(l => l.OBRA_obra_id == obraId && l.INMUEBLE.Any(i => i.DETALLE_CARTILLA.Any(dc => dc.CARTILLA_cartilla_id == id)))
                                    .Select(l => new { l.lote_id, l.abreviatura }).ToList(),
                    "lote_id", "abreviatura"
                );
                ViewBag.InmueblePorLote = new SelectList(
                    db.INMUEBLE.Where(i => i.LOTE_INMUEBLE.OBRA_obra_id == obraId && i.DETALLE_CARTILLA.Any(dc => dc.CARTILLA_cartilla_id == id))
                               .Select(i => new { i.inmueble_id, i.codigo_inmueble }).ToList(),
                    "inmueble_id", "codigo_inmueble"
                );

                ViewBag.SupervisorNames = db.USUARIO.ToDictionary(
            u => u.PERSONA_rut,
            u => $"{u.PERSONA.nombre} {u.PERSONA.apeliido_paterno} {u.PERSONA.apellido_materno}"
        );

                var rutSPV = ObtenerRutUsuarioAutenticado();
                ViewBag.RutUsuarioAutenticado = rutSPV;

                // Establecer la bandera global para indicar que se ha realizado una actualización
                actualizacionEditCartilla = true;

                return View(viewModel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult EditarCartilla(CartillasViewModel viewModel, List<DETALLE_CARTILLA> DetalleCartillas)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var dbContext = new ObraManzanoFinal())
                    {
                        // Actualizar la información de la Cartilla en la base de datos
                        dbContext.Entry(viewModel.Cartilla).State = EntityState.Modified;

                        // Obtener el rut del usuario autenticado
                        var rutSPV = ObtenerRutUsuarioAutenticado();

                        // Obtener los detalles existentes en la base de datos
                        var existingDetalles = dbContext.DETALLE_CARTILLA
                                                        .Where(d => d.CARTILLA_cartilla_id == viewModel.Cartilla.cartilla_id)
                                                        .ToList();

                        // Recorrer los detalles recibidos en el viewModel
                        foreach (var detalleCartilla in DetalleCartillas)
                        {
                           

                            var existingDetalle = existingDetalles.FirstOrDefault(d => d.detalle_cartilla_id == detalleCartilla.detalle_cartilla_id);
                            if (existingDetalle != null)
                            {
                                // Verificar si estado_supv ha cambiado y fecha_supv aún no está establecida
                                if (existingDetalle.estado_supv != detalleCartilla.estado_supv && existingDetalle.fecha_supv == null)
                                {
                                    existingDetalle.fecha_supv = DateTime.Now;
                                }

                                // Verificar cambios y actualizar solo si hay modificaciones
                                bool hasChanged = false;

                                if (existingDetalle.estado_supv != detalleCartilla.estado_supv)
                                {
                                    // Si estado_supv ya tiene un valor no nulo, no permitir cambios
                                    if (existingDetalle.estado_supv != null)
                                    {
                                        detalleCartilla.estado_supv = existingDetalle.estado_supv;
                                    }
                                    else
                                    {
                                        existingDetalle.estado_supv = detalleCartilla.estado_supv;
                                        hasChanged = true;

                                        // Si estado_supv cambia a true o false, asignar rut_spv solo si es null
                                        if ((detalleCartilla.estado_supv == true || detalleCartilla.estado_supv == false) && existingDetalle.rut_spv == null && !string.IsNullOrEmpty(rutSPV))
                                        {
                                            existingDetalle.rut_spv = rutSPV; // Almacenar el rut del usuario autenticado

Views/VistaPerfilSupervisor/Index.cshtml
@model IEnumerable<Proyecto_Cartilla_Autocontrol.Models.CARTILLA>

@{
    ViewBag.Title = "Index";
}

@if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Supervisor")
{
    Layout = "~/Views/Shared/_Layout_Supv.cshtml";
}
else
{
    Layout = "~/Views/Shared/_LayoutGeneral.cshtml";
}

@if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Supervisor")
{

    <link rel="stylesheet" href="~/Content/css/CRUD.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">


    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2>Gestión de <b>Cartillas de Autocontrol</b></h2>
                        </div>
                        <div class="col-sm-6">
                            <a id="editarCartillaBtn2"
                               href="@Url.Action("EditarCartillaMovilTest", "SupervisorMovil")" class="btn btn-warning">
                                <i class="material-icons">edit</i>
                                Revisión Cartilla
                            </a>
                          


                        </div>
                    </div>
                </div>
                <table id="cartillaTable" class="table table-striped table-hover">
                    <thead>
                        <tr>

                            <th style="white-space: nowrap;">Cartilla ID</th>
                            <th> Fecha </th>
                            <th> Obra </th>
                            <th> Código Actividad </th>
                            <th> Actividad </th>
                            <th> Estado Final </th>
                            <th> Estado </th>
                            <th>Revisión</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>

                                <td>  @Html.DisplayFor(modelItem => item.cartilla_id) </td>
                                <td>  @item.fecha.ToString("dd-MM-yyyy") </td>
                                <td>  @Html.DisplayFor(modelItem => item.OBRA.nombre_obra)</td>
                                <td>  @Html.DisplayFor(modelItem => item.ACTIVIDAD.codigo_actividad)</td>
                                <td>  @Html.DisplayFor(modelItem => item.ACTIVIDAD.nombre_actividad)</td>

                                <td>  @Html.DisplayFor(modelItem => item.ESTADO_FINAL.descripcion)</td>
                                <td>
                                    @if (item.ACTIVIDAD.estado == "B")
                                    {
                                        <i style="margin-left:18px;" class="material-icons" data-toggle="tooltip" title="Estado Bloqueado">&#xE897;</i>
                                    }
                                    else if (item.ACTIVIDAD.estado == "A")
                                    {
                                        <i style="margin-left:18px;" class="material-icons" data-toggle="tooltip" title="Estado Activo">&#xE898;</i>
                                    }
                                </td>


                                <td>
                                    @if (item.ACTIVIDAD.estado == "B")
                                    {
                                        <a href="#" class="edit edit-icon consulta-icon" data-url="@Url.Action("ConsultaRevision", "VistaPerfilSupervisor", new { id = item.cartilla_id })">
                                            <i class="material-icons" data-toggle="tooltip" title="Consulta de Revisión">&#xE8FD;</i>
                                            <span style="display: none;">Consulta</span>
                                        </a>

                                        <a href="#" class="edit edit-icon" data-url="#">
                                            <i style="color:dimgray;" class="material-icons" data-toggle="tooltip" title="La Cartilla no se puede modificar en Estado Bloqueado">&#xE254;</i>
                                            <span style="display: none;">Edit</span>
                                        </a>
                                    }
                                    else if (item.ACTIVIDAD.estado == "A")
                                    {
                                        if (item.DETALLE_CARTILLA.All(dc => dc.estado_supv != null))
                                        {

                                            <a href="#" class="edit edit-icon consulta-icon" data-url="@Url.Action("ConsultaRevision", "VistaPerfilSupervisor", new { id = item.cartilla_id })">
                                                <i class="material-icons" data-toggle="tooltip" title="Consulta de Revisión">&#xE8FD;</i>
                                                <span style="display: none;">Consulta</span>
                                            </a>

                                            <a href="#" class="edit edit-icon" data-url="@Url.Action("EditarCartilla", "VistaPerfilSupervisor", new { id = item.cartilla_id })">
                                                <i class="material-icons" data-toggle="tooltip" title="Aprobar Cartilla">&#xE254;</i>
                                                <span style="display: none;">Edit</span>
                                            </a>
                                        }
                                        else
                                        {

                                            <a href="#" class="edit edit-icon consulta-icon" data-url="@Url.Action("ConsultaRevision", "VistaPerfilSupervisor", new { id = item.cartilla_id })">
                                                <i class="material-icons" data-toggle="tooltip" title="Consulta de Revisión">&#xE8FD;</i>
                                                <span style="display: none;">Consulta</span>
                                            </a>

                                            <a href="#" class="edit edit-icon" data-url="@Url.Action("EditarCartilla", "VistaPerfilSupervisor", new { id = item.cartilla_id })">
                                                <i class="material-icons" data-toggle="tooltip" title="Aprobar Cartilla">&#xE254;</i>
                                                <span style="display: none;">Edit</span>
                                            </a>
                                        }
                                    }
                                </td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>

    if (TempData["ErrorMessage"] != null)
    {
        <script>
      $(document).ready(function () {
          alert('@TempData["ErrorMessage"]');
      });
        </script>
    }

    <script>
        $(document).ready(function () {
            $(".edit").click(function (e) {
                e.preventDefault(); // Prevenir el comportamiento predeterminado del enlace

                var url = $(this).data("url"); // Obtener la URL de data-url

                // Redirigir a la vista "Edit"
                window.location.href = url;
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $('#cartillaTable').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });
        });
    </script>
    <script>
        // Función que oculta o muestra el botón basado en el tamaño de la pantalla
        function mostrarBotonEnMovil2() {
            var anchoPantalla = window.innerWidth;
            var boton2 = document.getElementById("editarCartillaBtn2");

            // Definir el ancho máximo para dispositivos móviles y tabletas (768px es un valor común)
            if (anchoPantalla <= 768) {
                // Si el ancho de la pantalla es menor o igual a 768px (móvil o tableta), mostramos el botón
                boton2.style.display = 'block';
            } else {
                // Si es mayor, ocultamos el botón (escritorio)
                boton2.style.display = 'none';
            }
        }

        // Ejecutar la función al cargar la página
        mostrarBotonEnMovil2();

        // Ejecutar la función cuando el tamaño de la pantalla cambia (redimensionar)
        window.onresize = mostrarBotonEnMovil2;
    </script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            function toggleEditLinks() {
                const editLinks = document.querySelectorAll('.edit');
                const width = window.innerWidth;

                editLinks.forEach(link => {
                    if (width < 768) {
                        if (link.getAttribute('data-url') === "#") {
                            link.style.display = 'none'; // Oculta el enlace que no se puede modificar
                        } else if (link.getAttribute('data-url').includes("EditarCartilla")) {
                            link.style.display = 'none'; // Oculta el enlace para aprobar la cartilla
                        }
                    } else {
                        link.style.display = ''; // Muestra el enlace
                    }
                });
            }

            // Llama a la función al cargar la página
            toggleEditLinks();

            // Llama a la función cuando cambia el tamaño de la ventana
            window.addEventListener('resize', toggleEditLinks);
        });

    </script>

    <script>
 // Script para manejar la expiración de la sesión
 setTimeout(function () {
     window.location.href = '@Url.Action("Login", "Account")';
 }, 43200000); // 12 horas en milisegundos
    </script>


}

else
{
    <link rel="stylesheet" href="~/Content/css/AccesoDenegado.css">
    <div id="header">
        <h1> Acceso denegado. Esta vista solo está disponible para Supervisor</h1>
        <br />
        <a href="@Url.Action("Login", "Account")" class="btn-acceso">Iniciar Sesión</a>
    </div>
}