Controllers/CartillasAutocontrolFiltradoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proyecto_Cartilla_Autocontrol.Models;
using Proyecto_Cartilla_Autocontrol.Models.ViewModels;
using Rotativa;
using Rotativa.Options;
using System.Net.Mail;
using System.IO;
using System.Runtime.Remoting.Contexts;
using ClosedXML.Excel;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Web.UI;
using DocumentFormat.OpenXml.EMMA;
using iTextSharp.text.pdf;
using MoreLinq;
using System.Text.RegularExpressions;

namespace Proyecto_Cartilla_Autocontrol.Controllers
{
    public class CartillasAutocontrolFiltradoController : Controller
    {
        private ObraManzanoFinal db = new ObraManzanoFinal();
        public async Task<ActionResult> ListaCartillasPorActividad()
        {
            if (Session["UsuarioAutenticado"] != null)
            {
                var usuarioAutenticado = (USUARIO)Session["UsuarioAutenticado"];
                ViewBag.UsuarioAutenticado = usuarioAutenticado;

                // Obtener la lista de IDs de obras a las que el usuario tiene acceso
                var obrasAcceso = db.ACCESO_OBRAS
                    .Where(a => a.usuario_id == usuarioAutenticado.usuario_id)
                    .Select(a => a.obra_id)
                    .ToList();

                // Obtener las cartillas para las obras a las que el usuario tiene acceso
                var detalleCartillas = db.DETALLE_CARTILLA
                    .Include(d => d.ITEM_VERIF)
                    .Include(d => d.CARTILLA.ACTIVIDAD.OBRA.RESPONSABLE)
                    .Include(d => d.CARTILLA)
                    .Where(d => obrasAcceso.Contains(d.CARTILLA.ACTIVIDAD.OBRA_obra_id))
                    .Where(d => d.CARTILLA.ACTIVIDAD_actividad_id == d.CARTILLA.ACTIVIDAD.actividad_id);

                return View(await detalleCartillas.ToListAsync());
            }
            else
            {
                // Maneja el caso en el que el usuario no esté autenticado correctamente
                return RedirectToAction("Login", "Account"); // Redirige a la página de inicio de sesión u otra página adecuada
            }
        }

        public async Task<ActionResult> LoteDetails(int cartillaId)
        {
            if (Session["UsuarioAutenticado"] != null)
            {
                var usuarioAutenticado = (USUARIO)Session["UsuarioAutenticado"];
                ViewBag.UsuarioAutenticado = usuarioAutenticado;

                var obrasAcceso = db.ACCESO_OBRAS
                    .Where(a => a.usuario_id == usuarioAutenticado.usuario_id)
                    .Select(a => a.obra_id)
                    .ToList();

                var cartilla = await db.CARTILLA.FindAsync(cartillaId);
                if (cartilla == null)
                {
                    return HttpNotFound(); // O maneja la situación de evento no encontrado de la forma que prefieras
                }

                var obraSeleccionada = await db.OBRA.FindAsync(cartilla.OBRA_obra_id);
                if (obraSeleccionada == null || !obrasAcceso.Contains(obraSeleccionada.obra_id))
                {
                    return HttpNotFound(); // O maneja la situación de evento no encontrado de la forma que prefieras
                }

                var items = await db.LOTE_INMUEBLE
                    .Where(a => a.OBRA_obra_id == obraSeleccionada.obra_id && obrasAcceso.Contains(a.OBRA_obra_id))
                    .ToListAsync();

                var loteStatus = new Dictionary<int, bool>();

                foreach (var item in items)
                {
                    bool tieneDetalleCartilla = LoteTieneDetalleCartilla(item.lote_id, cartillaId);
                    loteStatus[item.lote_id] = tieneDetalleCartilla;
                }

                ViewBag.ObraSeleccionado = obraSeleccionada;
                ViewBag.LoteStatus = loteStatus;
                ViewBag.CartillaId = cartillaId; // Agregar CartillaId a ViewBag
                ViewBag.NombreActividad = cartilla.ACTIVIDAD.nombre_actividad;

                return View(items);
            }
            else
            {
                // Maneja el caso en el que el usuario no esté autenticado correctamente
                return RedirectToAction("Login", "Account"); // Redirige a la página de inicio de sesión u otra página adecuada
            }
        }


        public async Task<ActionResult> LoteDetailsSupervisor(int cartillaId)
        {
            if (Session["UsuarioAutenticado"] != null)
            {
                var usuarioAutenticado = (USUARIO)Session["UsuarioAutenticado"];
                ViewBag.UsuarioAutenticado = usuarioAutenticado;

                var obrasAcceso = db.ACCESO_OBRAS
                    .Where(a => a.usuario_id == usuarioAutenticado.usuario_id)
                    .Select(a => a.obra_id)
                    .ToList();

                var cartilla = await db.CARTILLA.FindAsync(cartillaId);
                if (cartilla == null)
                {
                    return HttpNotFound(); // O maneja la situación de evento no encontrado de la forma que prefieras
                }

                var obraSeleccionada = await db.OBRA.FindAsync(cartilla.OBRA_obra_id);
                if (obraSeleccionada == null || !obrasAcceso.Contains(obraSeleccionada.obra_id))
                {
                    return HttpNotFound(); // O maneja la situación de evento no encontrado de la forma que prefieras
                }

                var items = await db.LOTE_INMUEBLE
                    .Where(a => a.OBRA_obra_id == obraSeleccionada.obra_id && obrasAcceso.Contains(a.OBRA_obra_id))
                    .ToListAsync();

                var loteStatus = new Dictionary<int, bool>();

                foreach (var item in items)
                {
                    bool tieneDetalleCartilla = LoteTieneDetalleCartilla(item.lote_id, cartillaId);
                    loteStatus[item.lote_id] = tieneDetalleCartilla;
                }

                ViewBag.ObraSeleccionado = obraSeleccionada;
                ViewBag.LoteStatus = loteStatus;
                ViewBag.CartillaId = cartillaId; // Agregar CartillaId a ViewBag

                return View(items);
            }
            else
            {
                // Maneja el caso en el que el usuario no esté autenticado correctamente
                return RedirectToAction("Login", "Account"); // Redirige a la página de inicio de sesión u otra página adecuada
            }
        }

        private bool LoteTieneDetalleCartilla(int loteId, int cartillaId)
        {
            return db.DETALLE_CARTILLA
                .Any(d => d.CARTILLA_cartilla_id == cartillaId &&
                          db.INMUEBLE.Any(i => i.LOTE_INMUEBLE_lote_id == loteId && d.INMUEBLE_inmueble_id == i.inmueble_id));
        }

        public async Task<ActionResult> ListaCartillasSupervisor()
        {
            if (Session["UsuarioAutenticado"] != null)
            {
                var usuarioAutenticado = (USUARIO)Session["UsuarioAutenticado"];
                ViewBag.UsuarioAutenticado = usuarioAutenticado;

                // Obtener la lista de IDs de obras a las que el usuario tiene acceso
                var obrasAcceso = db.ACCESO_OBRAS
                    .Where(a => a.usuario_id == usuarioAutenticado.usuario_id)
                    .Select(a => a.obra_id)
                    .ToList();

                // Obtener la lista de IDs de cartillas a las que el usuario tiene acceso
                var cartillasAcceso = db.ACCESO_CARTILLA
                    .Where(ac => ac.USUARIO_usuario_id == usuarioAutenticado.usuario_id)
                    .Select(ac => ac.CARTILLA_cartilla_id)
                    .ToList();

                // Obtener las cartillas para las obras a las que el usuario tiene acceso
                var detalleCartillas = db.DETALLE_CARTILLA
                    .Include(d => d.ITEM_VERIF)
                    .Include(d => d.CARTILLA.ACTIVIDAD.OBRA.RESPONSABLE)
                    .Include(d => d.CARTILLA)
                    .Where(d => obrasAcceso.Contains(d.CARTILLA.ACTIVIDAD.OBRA_obra_id))
                    .Where(d => d.CARTILLA.ACTIVIDAD_actividad_id == d.CARTILLA.ACTIVIDAD.actividad_id)
                    .Where(d => cartillasAcceso.Contains(d.CARTILLA.cartilla_id)); // Filtra por las cartillas a las que tiene acceso

                return View(await detalleCartillas.ToListAsync());
            }
            else
            {
                // Maneja el caso en el que el usuario no esté autenticado correctamente
                return RedirectToAction("Login", "Account"); // Redirige a la página de inicio de sesión u otra página adecuada
            }
        }

        public static (string, int) SplitLabel(string label)
        {
            string nonNumericPart = string.Concat(label.TakeWhile(char.IsLetter));
            int numericPart = int.Parse(string.Concat(label.SkipWhile(char.IsLetter)));
            return (nonNumericPart, numericPart);
        }

        // Comparador personalizado para ordenar los labels
        public class LabelComparer : IComparer<string>
        {
            public int Compare(string x, string y)
            {
                var splitX = SplitLabel(x);
                var splitY = SplitLabel(y);

                // Primero comparar las partes no numéricas
                int nonNumericComparison = string.Compare(splitX.Item1, splitY.Item1);
                if (nonNumericComparison != 0)
                    return nonNumericComparison;

                // Luego comparar las partes numéricas
                return splitX.Item2.CompareTo(splitY.Item2);
            }
        }

        public ActionResult ExportToExcel(int cartillaId, int actividadId)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

Views/CartillasAutocontrolFiltrado/LoteDetails.cshtml
@model IEnumerable<Proyecto_Cartilla_Autocontrol.Models.LOTE_INMUEBLE>

@{
    ViewBag.Title = "Index";
    var obraSeleccionada = ViewBag.ObraSeleccionado as Proyecto_Cartilla_Autocontrol.Models.OBRA;
    var cartillaId = ViewBag.CartillaId; // Obtener CartillaId del ViewBag
}

@if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Autocontrol")
{
    Layout = "~/Views/Shared/_Layout_Autocontrol.cshtml";
}
else if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Supervisor")
{
    Layout = "~/Views/Shared/_Layout_Supv.cshtml";
}
else if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Consulta")
{
    Layout = "~/Views/Shared/_Layout_Consulta.cshtml";
}
else
{
    Layout = "~/Views/Shared/_LayoutGeneral.cshtml";
}

@if (Session["Perfil"] != null && (Session["Perfil"].ToString() == "Autocontrol" || Session["Perfil"].ToString() == "Consulta" || Session["Perfil"].ToString() == "Supervisor"))
{
    <link rel="stylesheet" href="~/Content/css/CRUD.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">

    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2>Lista de Lotes de Inmueble de la Obra: <b>@obraSeleccionada.nombre_obra</b> y Cartilla ID: <b> @cartillaId</b> de la Actividad  <b>@ViewBag.NombreActividad</b> </h2>
                        </div>
                        <div class="col-sm-6">
                            <a href="@Url.Action("ListaCartillasPorActividad", "CartillasAutocontrolFiltrado")" class="btn btn-success">
                                <i class="material-icons">arrow_back</i>
                                Volver
                            </a>
                        </div>
                    </div>
                </div>
                <table id="cartillaTable" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Tipo de Bloque</th>
                            <th>Abreviatura</th>
                            <th>Rango Inicial</th>
                            <th>Rango Final</th>
                            <th>Cantidad de Pisos</th>
                            <th>Cantidad de Inmuebles</th>
                            <th>Descargar Cartilla</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            bool tieneDetalleCartilla = ViewBag.LoteStatus.ContainsKey(item.lote_id) && ViewBag.LoteStatus[item.lote_id];
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.tipo_bloque)</td>
                                <td>@Html.DisplayFor(modelItem => item.abreviatura)</td>
                                <td> @(item.rango_inicial.HasValue ? Convert.ToInt32(Math.Floor(item.rango_inicial.Value)) : 0) </td>
                                <td> @(item.rango_final.HasValue ? Convert.ToInt32(Math.Floor(item.rango_final.Value)) : 0) </td>
                                <td> @(item.cantidad_pisos.HasValue ? Convert.ToInt32(Math.Floor(item.cantidad_pisos.Value)) : 0) </td>
                                <td> @Convert.ToInt32(Math.Floor(item.cantidad_inmuebles)) </td>
                                <td>
                                    <div class="dropdown">
                                        <a href="#" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                            <i class="material-icons" data-toggle="tooltip" title="Descargar Cartilla">&#xE2C4;</i>
                                            <span style="display: none;">Descargar</span>
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <li>
                                                <a class="dropdown-item" href="@Url.Action("GenerarPdfPorLote", new { cartilla_id = @cartillaId, lote_id =  item.lote_id})">
                                                    Descargar Cartilla Formato Cartilla
                                                </a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" href="@Url.Action("GenerarPdfPorLote2", new { cartilla_id = @cartillaId, lote_id =  item.lote_id})">
                                                    Descargar Cartilla Formato Serviu
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $(".edit").click(function (e) {
                e.preventDefault();
                var url = $(this).data("url");
                window.location.href = url;
            });

            $(".delete").click(function (e) {
                e.preventDefault();
                var url = $(this).data("url");
                window.location.href = url;
            });

            $('#cartillaTable').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });

            // Script para manejar la expiración de la sesión
            setTimeout(function () {
                window.location.href = '@Url.Action("Login", "Account")';
            }, 43200000); // 12 horas en milisegundos
        });
    </script>
}
else
{
    <link rel="stylesheet" href="~/Content/css/AccesoDenegado.css">
    <div id="header">
        <h1> Acceso denegado. Esta vista es privada</h1>
        <br />
        <a href="@Url.Action("Login", "Account")" class="btn btn-primary">Iniciar sesión</a>
    </div>
}

Views/CartillasAutocontrolFiltrado/LoteDetailsSupervisor.cshtml
@model IEnumerable<Proyecto_Cartilla_Autocontrol.Models.LOTE_INMUEBLE>

@{
    ViewBag.Title = "Index";
    var obraSeleccionada = ViewBag.ObraSeleccionado as Proyecto_Cartilla_Autocontrol.Models.OBRA;
    var cartillaId = ViewBag.CartillaId; // Obtener CartillaId del ViewBag
}

@if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Autocontrol")
{
    Layout = "~/Views/Shared/_Layout_Autocontrol.cshtml";
}
else if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Supervisor")
{
    Layout = "~/Views/Shared/_Layout_Supv.cshtml";
}
else if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Consulta")
{
    Layout = "~/Views/Shared/_Layout_Consulta.cshtml";
}
else
{
    Layout = "~/Views/Shared/_LayoutGeneral.cshtml";
}

@if (Session["Perfil"] != null && (Session["Perfil"].ToString() == "Autocontrol" || Session["Perfil"].ToString() == "Consulta" || Session["Perfil"].ToString() == "Supervisor"))
{
    <link rel="stylesheet" href="~/Content/css/CRUD.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">

    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2>Lista de Lotes de Inmueble de la Obra: <b>@obraSeleccionada.nombre_obra</b> y Cartilla ID: <b> @cartillaId</b></h2>

                        </div>
                        <div class="col-sm-6">
                            <a href="@Url.Action("ListaCartillasSupervisor", "CartillasAutocontrolFiltrado")" class="btn btn-success">
                                <i class="material-icons">arrow_back</i>
                                Volver
                            </a>
                        </div>
                    </div>
                </div>
                <table id="cartillaTable" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Tipo de Bloque</th>
                            <th>Abreviatura</th>
                            <th>Rango Inicial</th>
                            <th>Rango Final</th>
                            <th>Cantidad de Pisos</th>
                            <th>Cantidad de Inmuebles</th>
                            <th>Descargar Cartilla</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            bool tieneDetalleCartilla = ViewBag.LoteStatus.ContainsKey(item.lote_id) && ViewBag.LoteStatus[item.lote_id];
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.tipo_bloque)</td>
                                <td>@Html.DisplayFor(modelItem => item.abreviatura)</td>
                                <td> @(item.rango_inicial.HasValue ? Convert.ToInt32(Math.Floor(item.rango_inicial.Value)) : 0) </td>
                                <td> @(item.rango_final.HasValue ? Convert.ToInt32(Math.Floor(item.rango_final.Value)) : 0) </td>
                                <td> @(item.cantidad_pisos.HasValue ? Convert.ToInt32(Math.Floor(item.cantidad_pisos.Value)) : 0) </td>
                                <td> @Convert.ToInt32(Math.Floor(item.cantidad_inmuebles)) </td>
                                <td>
                                    <div class="dropdown">
                                        <a href="#" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                            <i class="material-icons" data-toggle="tooltip" title="Descargar Cartilla">&#xE2C4;</i>
                                            <span style="display: none;">Descargar</span>
                                        </a>

                                       

                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <li>
                                                <a class="dropdown-item" href="@Url.Action("GenerarPdfPorLote", new { cartilla_id = @cartillaId, lote_id =  item.lote_id})">
                                                    Descargar Cartilla Formato Cartilla
                                                </a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" href="@Url.Action("GenerarPdfPorLote2", new { cartilla_id = @cartillaId, lote_id =  item.lote_id})">
                                                    Descargar Cartilla Formato Serviu
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $(".edit").click(function (e) {
                e.preventDefault();
                var url = $(this).data("url");
                window.location.href = url;
            });

            $(".delete").click(function (e) {
                e.preventDefault();
                var url = $(this).data("url");
                window.location.href = url;
            });

            $('#cartillaTable').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });

            // Script para manejar la expiración de la sesión
            setTimeout(function () {
                window.location.href = '@Url.Action("Login", "Account")';
            }, 43200000); // 12 horas en milisegundos
        });
    </script>
}
else
{
    <link rel="stylesheet" href="~/Content/css/AccesoDenegado.css">
    <div id="header">
        <h1> Acceso denegado. Esta vista es privada</h1>
        <br />
        <a href="@Url.Action("Login", "Account")" class="btn btn-primary">Iniciar sesión</a>
    </div>
}