Controllers/AdjuntarDocumentoController.cs
using Proyecto_Cartilla_Autocontrol.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data;
using System.Threading.Tasks;



namespace Proyecto_Cartilla_Autocontrol.Controllers
{
    public class AdjuntarDocumentoController : Controller
    {
        private ObraManzanoFinal db = new ObraManzanoFinal();


        public async Task<ActionResult> GestionarDocumento(int id)
        {
            var cartillaSeleccionada = await db.CARTILLA.FindAsync(id);
            if (cartillaSeleccionada == null)
            {
                return HttpNotFound();
            }
            ViewBag.CartillaSeleccionada = cartillaSeleccionada;

            var detalleCartilla = db.DETALLE_CARTILLA
                .Include(d => d.ITEM_VERIF)
                .Include(d => d.CARTILLA)
                .Where(d => d.CARTILLA.cartilla_id == id)
                .ToList();

            // Obtener la ruta de la carpeta donde están los documentos
            string folderPath = Server.MapPath("~/Content/documento/" + id);
            ViewBag.Documentos = Directory.Exists(folderPath) ? Directory.GetFiles(folderPath) : new string[0];

            // Comprobar si la carpeta existe y contiene archivos
            bool hayArchivos = Directory.Exists(folderPath) && Directory.GetFiles(folderPath).Any();

            // Guardar el valor en ViewBag
            ViewBag.HayArchivos = hayArchivos;

            return View(detalleCartilla);
        }


        [HttpPost]
        public ActionResult AdjuntarDocumento(IEnumerable<HttpPostedFileBase> files, int cartillaId)
        {
            if (files != null && files.Any(f => f != null && f.ContentLength > 0))
            {
                try
                {
                    // Crear la ruta de la subcarpeta específica para la cartilla
                    string folderPath = "~/Content/documento/" + cartillaId;  // La subcarpeta específica para la cartilla
                    string physicalFolderPath = Server.MapPath(folderPath);

                    // Verificar si la carpeta ya existe
                    if (!Directory.Exists(physicalFolderPath))
                    {
                        Directory.CreateDirectory(physicalFolderPath);
                    }

                    foreach (var file in files)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            string fileName = Path.GetFileNameWithoutExtension(file.FileName); // Nombre sin extensión
                            string fileExtension = Path.GetExtension(file.FileName); // Extensión del archivo
                            string physicalPath = Path.Combine(physicalFolderPath, file.FileName);
                            int fileCount = 1;

                            // Verificar si el archivo ya existe y generar un nombre nuevo si es necesario
                            while (System.IO.File.Exists(physicalPath))
                            {
                                fileCount++;
                                string newFileName = $"{fileName} ({fileCount}){fileExtension}";
                                physicalPath = Path.Combine(physicalFolderPath, newFileName);
                            }

                            // Guardar el archivo en la subcarpeta de la cartilla con el nombre nuevo (si es necesario)
                            file.SaveAs(physicalPath);
                        }
                    }

                    // Guardar la ruta de la carpeta en la base de datos (no de un archivo individual)
                    var cartilla = db.CARTILLA.Find(cartillaId);
                    if (cartilla != null)
                    {
                        cartilla.ruta_pdf = folderPath;  // Guardar la ruta de la carpeta donde están los archivos
                        db.SaveChanges();
                    }

                    // Redirigir a la vista GestionarDocumento con el ID de la cartilla
                    return RedirectToAction("GestionarDocumento", new { id = cartillaId });
                }
                catch (Exception ex)
                {
                    // Manejar cualquier excepción que pueda ocurrir durante la subida de archivos
                    ViewBag.Error = "Hubo un error al subir los archivos: " + ex.Message;
                }
            }
            else
            {
                ViewBag.Error = "Por favor, seleccione al menos un archivo.";
            }

            // En caso de error, redirigir a la vista GestionarDocumento con el ID de la cartilla
            return RedirectToAction("GestionarDocumento", new { id = cartillaId });
        }


        public ActionResult GetDocumentosAdjuntos(int cartillaId)
        {
            var cartilla = db.CARTILLA.Find(cartillaId);
            if (cartilla != null && !string.IsNullOrEmpty(cartilla.ruta_pdf))
            {
                string physicalFolderPath = Server.MapPath(cartilla.ruta_pdf);

                if (Directory.Exists(physicalFolderPath))
                {
                    var archivos = Directory.GetFiles(physicalFolderPath)
                                            .Select(f => Path.GetFileName(f))
                                            .ToList();
                    return Json(archivos, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new List<string>(), JsonRequestBehavior.AllowGet);
        }





        public async Task<ActionResult> GestionarDocumentoFiltrado(int id)
        {

            var cartillaSeleccionada = await db.CARTILLA.FindAsync(id);
            if (cartillaSeleccionada == null)
            {
                return HttpNotFound(); // O maneja la situación de evento no encontrado de la forma que prefieras
            }
            ViewBag.CartillaSeleccionada = cartillaSeleccionada;

            var detalleCartilla = db.DETALLE_CARTILLA.Include(d => d.ITEM_VERIF).Include(d => d.CARTILLA).Where(d => d.CARTILLA.cartilla_id == id).ToList();

            // Obtener la ruta de la carpeta donde están los documentos
            string folderPath = Server.MapPath("~/Content/documento/" + id);
            ViewBag.Documentos = Directory.Exists(folderPath) ? Directory.GetFiles(folderPath) : new string[0];

            // Comprobar si la carpeta existe y contiene archivos
            bool hayArchivos = Directory.Exists(folderPath) && Directory.GetFiles(folderPath).Any();

            // Guardar el valor en ViewBag
            ViewBag.HayArchivos = hayArchivos;

            return View(detalleCartilla);
        }


        [HttpPost]
        public ActionResult AdjuntarDocumentoFiltrado(IEnumerable<HttpPostedFileBase> files, int cartillaId)
        {
            if (files != null && files.Any(f => f != null && f.ContentLength > 0))
            {
                try
                {
                    // Crear la ruta de la subcarpeta específica para la cartilla
                    string folderPath = "~/Content/documento/" + cartillaId;  // La subcarpeta específica para la cartilla
                    string physicalFolderPath = Server.MapPath(folderPath);

                    // Verificar si la carpeta ya existe
                    if (!Directory.Exists(physicalFolderPath))
                    {
                        Directory.CreateDirectory(physicalFolderPath);
                    }

                    foreach (var file in files)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            string fileName = Path.GetFileNameWithoutExtension(file.FileName); // Nombre sin extensión
                            string fileExtension = Path.GetExtension(file.FileName); // Extensión del archivo
                            string physicalPath = Path.Combine(physicalFolderPath, file.FileName);
                            int fileCount = 1;

                            // Verificar si el archivo ya existe y generar un nombre nuevo si es necesario
                            while (System.IO.File.Exists(physicalPath))
                            {
                                fileCount++;
                                string newFileName = $"{fileName} ({fileCount}){fileExtension}";
                                physicalPath = Path.Combine(physicalFolderPath, newFileName);
                            }

                            // Guardar el archivo en la subcarpeta de la cartilla con el nombre nuevo (si es necesario)
                            file.SaveAs(physicalPath);
                        }
                    }

                    // Guardar la ruta de la carpeta en la base de datos (no de un archivo individual)
                    var cartilla = db.CARTILLA.Find(cartillaId);
                    if (cartilla != null)
                    {
                        cartilla.ruta_pdf = folderPath;  // Guardar la ruta de la carpeta donde están los archivos
                        db.SaveChanges();
                    }

                    // Redirigir a la vista GestionarDocumento con el ID de la cartilla
                    return RedirectToAction("GestionarDocumentoFiltrado", new { id = cartillaId });
                }
                catch (Exception ex)
                {
                    // Manejar cualquier excepción que pueda ocurrir durante la subida de archivos
                    ViewBag.Error = "Hubo un error al subir los archivos: " + ex.Message;
                }
            }
            else
            {
                ViewBag.Error = "Por favor, seleccione al menos un archivo.";
            }

            // En caso de error, redirigir a la vista GestionarDocumento con el ID de la cartilla
            return RedirectToAction("GestionarDocumentoFiltrado", new { id = cartillaId });
        }
        
       

Views/AdjuntarDocumento/GestionarDocumentoFiltrado.cshtml
@model IEnumerable<Proyecto_Cartilla_Autocontrol.Models.DETALLE_CARTILLA>

@{
    ViewBag.Title = "Index";
    var cartillaSeleccionada = ViewBag.CartillaSeleccionada as Proyecto_Cartilla_Autocontrol.Models.CARTILLA;
}

@if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Autocontrol")
{
    Layout = "~/Views/Shared/_Layout_Autocontrol.cshtml";
}
else if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Supervisor")
{
    Layout = "~/Views/Shared/_Layout_Supv.cshtml";
}
else if (Session["Perfil"] != null && Session["Perfil"].ToString() == "Consulta")
{
    Layout = "~/Views/Shared/_Layout_Consulta.cshtml";
}
else
{
    Layout = "~/Views/Shared/_LayoutGeneral.cshtml";
}

@if (Session["Perfil"] != null && (Session["Perfil"].ToString() == "Autocontrol" || Session["Perfil"].ToString() == "Consulta" || Session["Perfil"].ToString() == "Supervisor"))
{
    <link rel="stylesheet" href="~/Content/css/CRUD.css">
    <link rel="stylesheet" href="~/Content/css/basurerito.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">


    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2> Cartilla de Autocontrol ID: <b>@cartillaSeleccionada.cartilla_id</b></h2>
                        </div>
                        <div class="col-sm-6">
                            <a href="@Url.Action("ListaCartillasPorActividad", "CartillasAutocontrolFiltrado")" class="btn btn-success">
                                <i class="material-icons">arrow_back</i>
                                Volver
                            </a>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>

                            <th style="white-space: nowrap;"> Obra</th>
                            <th style="white-space: nowrap;"> Código Actividad</th>
                            <th style="white-space: nowrap;"> Actividad</th>

                            <th>Adjuntar Documento </th>
                            <th style="white-space: nowrap;">Descargar Documento</th>
                        </tr>
                    </thead>
                    <tbody>


                        @if (Model.Any())
                        {
                            int currentActivityId = -1; // Variable para llevar el seguimiento de la actividad actual

                            foreach (var item in Model)
                            {
                                if (item.CARTILLA.ACTIVIDAD.actividad_id != currentActivityId)
                                {
                                    // Iniciar una nueva fila para la actividad
                                    <tr>

                                        <td style="white-space: nowrap;">@item.CARTILLA.OBRA.nombre_obra</td>
                                        <td style="white-space: nowrap;">@item.CARTILLA.ACTIVIDAD.codigo_actividad</td>
                                        <td>@item.CARTILLA.ACTIVIDAD.nombre_actividad</td>

                                        <td>
                                            <form action="@Url.Action("AdjuntarDocumentoFiltrado", "AdjuntarDocumento")" method="post" enctype="multipart/form-data" style="display: flex; flex-direction: column; align-items: center;">
                                                <label for="file" style="cursor: pointer; margin-bottom: 10px; padding: 8px 10px; background-color: #F07124; border: 2px solid #ccc; color: #ffffff; font-size: 14px; border-radius: 5px;" onmouseover="this.style.backgroundColor='#6b6b6b';" onmouseout="this.style.backgroundColor='#F07124';">Seleccionar archivos</label>
                                                <input type="file" name="files" id="file" style="display: none;" multiple onchange="displayFileName(this)" />
                                                <span id="file-selected" style="margin-bottom: 10px;">Ningún archivo seleccionado</span>
                                                <input type="hidden" name="cartillaId" value="@item.CARTILLA.cartilla_id" />
                                                <input type="submit" value="Adjuntar Archivos" style="margin-top: 10px; padding: 8px 10px; background-color: #808080; border: 2px solid #ccc; color: #ffffff; font-size: 14px; border-radius: 5px;" onmouseover="this.style.backgroundColor='#6b6b6b';" onmouseout="this.style.backgroundColor='#808080';" />
                                            </form>
                                        </td>


                                        <td>
                                            @if (ViewBag.HayArchivos == true)
                                            {
                                                <div class="dropdown">
                                                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" style="background-color:#F07124; color:white;" aria-expanded="false">
                                                        Descargar Documentos
                                                    </button>
                                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                        @foreach (var filePath in ViewBag.Documentos)
                                                        {
                                                            var fileName = Path.GetFileName(filePath);
                                                            <li class="menu-basurero">
                                                                <a class="dropdown-item" href="@Url.Content("~/Content/documento/" + cartillaSeleccionada.cartilla_id + "/" + fileName)" download>
                                                                    @fileName
                                                                </a>
                                                                <button class="btn btn-danger btn-sm" onclick="eliminarArchivo('@fileName', '@cartillaSeleccionada.cartilla_id')" title="Eliminar archivo">
                                                                    <i class="fas fa-trash-alt"></i>
                                                                </button>
                                                            </li>
                                                        }
                                                    </ul>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="dropdown">
                                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                                        No hay documentos Disponibles
                                                    </button>
                                                </div>
                                            }
                                        </td>



                                    </tr>
                                    currentActivityId = item.CARTILLA.ACTIVIDAD.actividad_id; // Actualizar la actividad actual
                                }

                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>

    <script>
        function displayFileName(input) {
            var fileSelectedSpan = document.getElementById('file-selected');
            var files = input.files;
            if (files.length > 0) {
                var fileNames = Array.from(files).map(f => f.name).join(', ');
                fileSelectedSpan.textContent = fileNames;
            } else {
                fileSelectedSpan.textContent = 'Ningún archivo seleccionado';
            }
        }
    </script>
    <script>
        $(document).ready(function () {
            $(".edit").click(function (e) {
                e.preventDefault(); // Prevenir el comportamiento predeterminado del enlace

                var url = $(this).data("url"); // Obtener la URL de data-url

                // Redirigir a la vista "Edit"
                window.location.href = url;
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $(".VerCartilla").click(function (e) {
                e.preventDefault(); // Prevenir el comportamiento predeterminado del enlace

                var url = $(this).data("url"); // Obtener la URL de data-url

                // Redirigir a la vista "Edit"
                window.location.href = url;
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $(".delete").click(function (e) {
                e.preventDefault(); // Prevenir el comportamiento predeterminado del enlace

                var url = $(this).data("url"); // Obtener la URL de data-url

                // Redirigir a la vista "Edit"
                window.location.href = url;
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('#cartillaTable').DataTable({
                "processing": true,
                "serverSide": false, // Puedes cambiar a true si manejas grandes conjuntos de datos
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    }
                },
                "columns": [
                    { "data": "CARTILLA.cartilla_id" }, // Asegúrate de tener la ruta correcta a tus datos
                    { "data": "CARTILLA.fecha" },
                    { "data": "CARTILLA.ACTIVIDAD.codigo_actividad" },
                    { "data": "CARTILLA.OBRA.nombre_obra" },
                    { "data": "CARTILLA.ACTIVIDAD.estado" },
                    // ... otras columnas si las hay ...
                    {
                        "data": null,
                        "render": function (data, type, row) {
                            // Puedes personalizar la columna de acciones aquí
                            return '<a href="#" class="VerCartilla" data-url="' + row.CARTILLA.ACTIVIDAD_actividad_id + '">Ver Cartilla</a>';
                        }
                    }
                ]
            });
        });
    </script>
    <script>
  function eliminarArchivo(fileName, cartillaId) {
      if (confirm("¿Estás seguro de que deseas eliminar este archivo?")) {
          $.ajax({
              url: '@Url.Action("EliminarDocumento", "AdjuntarDocumento")', // Controlador y acción que manejará la eliminación
              type: 'POST',
              data: {
                  fileName: fileName,
                  cartillaId: cartillaId
              },
              success: function (result) {
                  if (result.success) {
                      alert('El archivo ha sido eliminado correctamente.');
                      location.reload(); // Recargar la página para actualizar la lista de archivos
                  } else {
                      alert('Error al eliminar el archivo.');
                  }
              },
              error: function () {
                  alert('Error en la petición.');
              }
          });
      }
  }
    </script>
    <script>
// Script para manejar la expiración de la sesión
setTimeout(function () {
    window.location.href = '@Url.Action("Login", "Account")';
}, 43200000); // 12 horas en milisegundos
    </script>
}

else
{
    <link rel="stylesheet" href="~/Content/css/AccesoDenegado.css">
    <div id="header">
        <h1> Acceso denegado. Vista Protegida</h1>
        <br />
        <a href="@Url.Action("Login", "Account")" class="btn-acceso">Iniciar Sesión</a>
    </div>
}